name: CI


on:
  push:
    branches:
      - master


jobs:
  build-and-push:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      # Tag commit para versão
      - name: Generate SHA
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> GITHUB_OUTPUT

          
      # Logar no container regyster
      - name: Login into the container registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_NAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

          
          
    # Realizar o Push para o Docker Hub
    # - name: Build docker image
    #   run: docker build -t hugossantos/nlw_journey_devops_api:${{steps.generate_sha.outputs.sha}} .
      #First form
      # - name: Push docker image
      #   run: |
      #    docker push hugossantos/nlw_journey_devops_api:${{steps.generate_sha.outputs.sha}}
      #    docker tag hugossantos/nlw_journey_devops_api:${{steps.generate_sha.outputs.sha}} hugossantos/nlw_journey_devops_api:latest
      #    docker push hugossantos/nlw_journey_devops_api:latest

      #Second Form
      - name: Build and Push docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            hugossantos/nlw_journey_devops_api:${{steps.generate_sha.outputs.sha}}
            hugossantos/nlw_journey_devops_api:latest