name: CI


on:
  push:
    branches:
      - master


jobs:
  build-and-push:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      # Tag commit para versão
      - name: Generate SHA
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> GITHUB_OUTPUT

          
      # Logar no container regyster
      - name: Login into the container registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_NAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      # Second Form
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
           ${{secrets.DOCKERHUB_NAME}}/journey:latest
           ${{secrets.DOCKERHUB_NAME}}/journey:${{steps.generate_sha.outputs.sha}}