name: CI

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: Build and Push with Tagged Version

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # Checkout code from repository

      - name: Generate SHA for Tag
        id: generate_sha
        run: |
          SHA=$(git rev-parse --short HEAD)  # Use git rev-parse for reliable SHA
          echo "SHA=$SHA" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_NAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Images
        uses: docker/build-push-action@v6
        with:
          context: .  # Build context (current directory)
          push: true  # Push images to Docker Hub
          tags: ${{ secrets.DOCKERHUB_NAME }}/journey:latest, ${{ secrets.DOCKERHUB_NAME }}/journey:${{ steps.generate_sha.outputs.SHA }}  # Use correct output variable

